---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: App Builder

on:
  workflow_call:
    inputs:
      app:
        type: string
        description: App Name
        required: true
      release:
        type: boolean
        description: Release
        required: true

jobs:
  plan:
    name: Plan
    runs-on:
      group: default
    outputs:
      app-exists: ${{ steps.app-exists.outputs.exists }}
      platforms: ${{ steps.app-options.outputs.platforms }}
    steps:
      - name: Checkout
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
        with:
          persist-credentials: false

      - name: Check For Existing App
        uses: ./.github/actions/app-exists
        id: app-exists
        with:
          app: ${{ inputs.app }}

      - name: Get App Options
        uses: ./.github/actions/app-options
        id: app-options
        with:
          app: ${{ inputs.app }}

      - name: Get App Versions
        uses: ./.github/actions/app-versions
        id: app-versions
        with:
          upstream-version: ${{ steps.app-options.outputs.version }}

      - name: Build App Metadata
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893
        id: meta
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          flavor: latest=false
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}
            ghcr.io/containerforge/${{ inputs.app }}
            quay.io/containerforge/${{ inputs.app }}
            oci.trueforge.org/containerforge/${{ inputs.app }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.app-versions.outputs.semantic }},enable=${{ steps.app-versions.outputs.is-valid-semver && inputs.release }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.app-versions.outputs.semantic }},enable=${{ steps.app-versions.outputs.is-valid-semver && inputs.release }}
            type=semver,pattern={{major}},value=${{ steps.app-versions.outputs.semantic }},enable=${{ steps.app-versions.outputs.is-valid-semver && inputs.release }}
            type=raw,value=${{ steps.app-versions.outputs.raw }},enable=${{ steps.app-versions.outputs.is-valid-semver && inputs.release }}
            type=raw,value=rolling,enable=${{ inputs.release }}
            type=raw,value=sandbox,enable=${{ ! inputs.release }}
            type=raw,value=sha-${{ github.sha }},enable=${{ inputs.release }}

      - name: Upload Bake Metadata
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: ${{ inputs.app }}-bake-metadata
          path: ${{ steps.meta.outputs.bake-file }}
          if-no-files-found: error
          retention-days: 1

  build:
    name: Build (${{ matrix.platform }})
    needs: plan
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(needs.plan.outputs.platforms) }}
    runs-on: ${{ startsWith(matrix.platform, 'linux/arm') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
        with:
          persist-credentials: false

      - name: Get Target Architecture
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
        id: target
        with:
          script: |-
            core.setOutput('arch', '${{ matrix.platform }}'.split('/').pop());

      - name: Get App Options
        uses: ./.github/actions/app-options
        id: app-options
        with:
          app: ${{ inputs.app }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@28fdb31ff34708d19615a74d67103ddc2ea9725c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Download Bake Metadata
        uses: actions/download-artifact@f093f21ca4cfa7c75ccbbc2be54da76a0c7e1f05
        with:
          name: ${{ inputs.app }}-bake-metadata
          path: ${{ runner.temp }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@1583c0f09d26c58c59d25b0eef29792b7ce99d9a

      - name: Add Include Directory to Build Context
        run: |-
          rsync -a --ignore-existing --progress ./include/ ./apps/${{ inputs.app }}/

      - name: Build App
        uses: docker/bake-action@41c10f2beb4c60ac3eb05f9d48947994b7ae47e5
        id: bake
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ runner.temp }}/docker-metadata-action-bake.json
          set: |
            *.args.VENDOR="TrueForge"
            *.cache-from=${{ format('type=registry,ref=ghcr.io/{0}/build_cache:{1}-{2},mode=max', github.repository_owner, inputs.app, steps.target.outputs.arch) }}
            *.cache-to=${{ inputs.release && format('type=registry,ref=ghcr.io/{0}/build_cache:{1}-{2},mode=max,compression=zstd,force-compression=true', github.repository_owner, inputs.app, steps.target.outputs.arch) || '' }}
            *.labels.org.opencontainers.image.title=${{ inputs.app }}
            *.labels.org.opencontainers.image.url=https://ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}
            *.labels.org.opencontainers.image.version=${{ steps.app-options.outputs.version }}
            *.labels.org.opencontainers.image.revision=${{ github.sha }}
            *.labels.org.opencontainers.image.vendor="TrueForge"
            *.labels.org.opencontainers.image.authors="TrueForge <info@trueforge.org>"
            *.labels.org.opencontainers.image.description="Container for ${{ inputs.app }} by TrueForge"
            *.output=type=image,name=ghcr.io/${{ github.repository_owner }}/${{ inputs.app }},push-by-digest=true,name-canonical=true,push=true,compression=zstd,force-compression=true
            *.platform=${{ matrix.platform }}
            *.tags=
          source: .
          targets: image
          workdir: ./apps/${{ inputs.app }}

      - name: Export Digest
        run: |-
          mkdir -p ${{ runner.temp }}/digests
          DIGEST="${{ fromJSON(steps.bake.outputs.metadata).image['containerimage.digest'] }}"
          echo "$DIGEST" > "${{ runner.temp }}/digests/${DIGEST#sha256:}"

      - name: Upload Digest
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: ${{ inputs.app }}-digests-${{ steps.target.outputs.arch }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1


  merge:
    name: Merge
    runs-on:
      group: default
    needs: build
    outputs:
      digest: ${{ steps.digest.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
        with:
          persist-credentials: false

      - name: Download Bake Metadata
        uses: actions/download-artifact@f093f21ca4cfa7c75ccbbc2be54da76a0c7e1f05
        with:
          name: ${{ inputs.app }}-bake-metadata
          path: ${{ runner.temp }}

      - name: Download Digests
        uses: actions/download-artifact@f093f21ca4cfa7c75ccbbc2be54da76a0c7e1f05
        with:
          path: ${{ runner.temp }}/digests
          pattern: ${{ inputs.app }}-digests-*
          merge-multiple: true

      - name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to Quay
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_CF_USER }}
          password: ${{ secrets.QUAY_CF_TOKEN }}

      - name: Create Multi-Arch Manifest List for GHCR
        working-directory: ${{ runner.temp }}/digests
        run: |-
          # Get GHCR tags
          GHCR_TAGS=$(jq -r --compact-output '.target."docker-metadata-action".tags
            | map(select(startswith("ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}")) | "-t " + .)
            | join(" ")' ${{ runner.temp }}/docker-metadata-action-bake.json)
          # Get Quay tags
          QUAY_TAGS=$(jq -r --compact-output '.target."docker-metadata-action".tags
            | map(select(startswith("quay.io/containerforge/'"${{ inputs.app }}"'")) | "-t " + .)
            | join(" ")' ${{ runner.temp }}/docker-metadata-action-bake.json)

          # Combine all tags
          ALL_TAGS="$QUAY_TAGS $GHCR_TAGS"

          # Create multi-arch manifest for all targets
          docker buildx imagetools create \
            $ALL_TAGS \
            $(printf 'ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}@sha256:%s ' *)
      - name: Inspect Image
        run: |-
          docker buildx imagetools inspect ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}:$(jq --raw-output '.target."docker-metadata-action".args.DOCKER_META_VERSION' ${{ runner.temp }}/docker-metadata-action-bake.json)

      - name: Export Digest
        id: digest
        run: |-
          TAG=$(jq --raw-output '.target."docker-metadata-action".args.DOCKER_META_VERSION' ${{ runner.temp }}/docker-metadata-action-bake.json)
          DIGEST=$(docker buildx imagetools inspect ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}:${TAG} --format '{{ json . }}' | jq --raw-output '.manifest.digest')
          echo "digest=${DIGEST}" >> $GITHUB_OUTPUT

      - name: Set Quay to Public
        if: github.event_name != 'pull_request'
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"visibility": "public"}' \
            -H "Authorization: Bearer ${{ secrets.QUAY_CF_API_TOKEN }}" \
            "https://quay.io/api/v1/repository/containerforge/${{ inputs.app }}/changevisibility"

  attest:
    name: Attest
    needs:
      - merge
    runs-on:
      group: default
    steps:

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to Quay
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_CF_USER }}
          password: ${{ secrets.QUAY_CF_TOKEN }}

      - name: Upload Dependency Snapshot to GHCR
        uses: anchore/sbom-action@8e94d75ddd33f69f691467e42275782e4bfefe84
        with:
          dependency-snapshot: true
          image: ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}@${{ needs.merge.outputs.digest }}

      - name: Upload Dependency Snapshot to Quay
        uses: anchore/sbom-action@8e94d75ddd33f69f691467e42275782e4bfefe84
        with:
          dependency-snapshot: true
          image: quay.io/containerforge/${{ inputs.app }}@${{ needs.merge.outputs.digest }}

      - name: Attestation for GHCR
        uses: actions/attest-build-provenance@ba965ac88abfc6fa49344893ed19e5bf479a07d6
        with:
          push-to-registry: true
          subject-name: ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}
          subject-digest: ${{ needs.merge.outputs.digest }}

      - name: Attestation for Quay
        uses: actions/attest-build-provenance@ba965ac88abfc6fa49344893ed19e5bf479a07d6
        with:
          push-to-registry: true
          subject-name: quay.io/containerforge/${{ inputs.app }}
          subject-digest: ${{ needs.merge.outputs.digest }}
      # TODO: reenable with gh cli added
      # - name: Verify Attestation for GHCR
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   run: |-
      #     gh attestation verify --repo ${{ github.repository }} oci://ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}@${{ needs.merge.outputs.digest }}

      ## TODO: fix
      # - name: Verify Attestation for QUAY
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   run: |-
      #     cosign verify-attestation --type slsaprovenance1 \
      #       --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
      #       --certificate-identity-regexp "^https://github.com/trueforge-org/containerforge/.github/workflows/app-builder.yaml@refs/heads/main" \
      #       quay.io/trueforge-org/${{ inputs.app }}@${{ needs.merge.outputs.digest }}

      ## TODO: check and/or fix
      # - name: Verify Attestation for TrueForge-OCI
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   run: |-
      #     cosign verify-attestation --type slsaprovenance1 \
      #       --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
      #       --certificate-identity-regexp "^https://github.com/trueforge-org/containerforge/.github/workflows/app-builder.yaml@refs/heads/main" \
      #       oci.trueforge.org/containeforge/${{ inputs.app }}@${{ needs.merge.outputs.digest }}
  sign:
    name: sign
    needs:
      - merge
    runs-on:
      group: default
    steps:

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to Quay
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_CF_USER }}
          password: ${{ secrets.QUAY_CF_TOKEN }}

      - name: Sign the merged digest for GHCR
        if: github.event_name != 'pull_request'
        run: |
          cosign sign ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}@${{ needs.merge.outputs.digest }} -y \
            -a "repo=${{ github.repository }}" \
            -a "workflow=${{ github.workflow }}" \
            -a "ref=${{ github.sha }}"

      - name: Sign the merged digest for Quay
        if: github.event_name != 'pull_request'
        run: |
          cosign sign quay.io/containerforge/${{ inputs.app }}@${{ needs.merge.outputs.digest }} -y \
            -a "repo=${{ github.repository }}" \
            -a "workflow=${{ github.workflow }}" \
            -a "ref=${{ github.sha }}"

      - name: Verify the signed digest on GHCR
        if: github.event_name != 'pull_request'
        run: |
          cosign verify ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}@${{ needs.merge.outputs.digest }} \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            --certificate-identity=https://github.com/trueforge-org/containerforge/.github/workflows/app-builder.yaml@refs/heads/main

      - name: Verify the signed digest on Quay
        if: github.event_name != 'pull_request'
        run: |
          cosign verify quay.io/containerforge/${{ inputs.app }}@${{ needs.merge.outputs.digest }} \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            --certificate-identity=https://github.com/trueforge-org/containerforge/.github/workflows/app-builder.yaml@refs/heads/main

  test:
    if: ${{ ! inputs.release }}
    name: Test
    needs:
      - merge
    runs-on:
      group: default
    steps:
      - name: Checkout
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
        with:
          persist-credentials: false

      - name: Generate Token
        uses: actions/create-github-app-token@b96fde71c0080358ed6e2d162f11c612c92a97d1
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Run App Tests
        uses: ./.github/actions/app-tests
        with:
          app: ${{ inputs.app }}
          image: ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}@${{ needs.merge.outputs.digest }}
          token: ${{ github.token }}

      - name: Get App Size Diff
        uses: ./.github/actions/app-size-diff
        id: app-size-diff
        with:
          from-app: ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}:rolling
          to-app: ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}:sandbox

      - name: Post App Size Diff
        uses: marocchino/sticky-pull-request-comment@fd19551a2a7c0d29677c63257f86d8ef8bb24b48
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          header: app-size-diff-${{ inputs.app }}
          message: |
            ${{ steps.app-size-diff.outputs.size-diff-markdown }}



  announce:
    if: ${{ inputs.release && needs.plan.outputs.app-exists != 'true' }}
    name: Announce
    needs:
      - plan
      - attest
      - sign
    runs-on:
      group: default
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Generate Token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Get App Options
        uses: ./.github/actions/app-options
        id: app-options
        with:
          app: ${{ inputs.app }}

      - name: Get Release Tag
        uses: ./.github/actions/release-tag
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Create Release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          body: |
            > [!NOTE]
            > A new app has been added.

            ## ðŸ“¦ App

            **Name**: [${{ inputs.app }}](https://github.com/${{ github.repository }}/pkgs/container/${{ inputs.app }})
            **Source**: <${{ steps.app-options.outputs.source }}>
          tag: ${{ steps.release.outputs.tag }}
          token: ${{ steps.app-token.outputs.token }}

  notify:
    if: ${{ inputs.release && !cancelled() }}
    needs:
      - plan
      - build
      - merge
      - attest
      - sign
      - announce
    name: Notify
    runs-on:
      group: default
    steps:
      - if: ${{ contains(needs.*.result, 'failure') }}
        name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - if: ${{ contains(needs.*.result, 'failure') }}
        name: Get App Options
        uses: ./.github/actions/app-options
        id: app-options
        with:
          app: ${{ inputs.app }}

      - if: ${{ contains(needs.*.result, 'failure') }}
        name: Send Discord Webhook
        uses: sarisia/actions-status-discord@11a0bfe3b50977e38aa2bd4a4ebd296415e83c19 # v1.15.4
        with:
          color: "0xFF0000"
          description: |
            App: `${{ inputs.app }}`
            Version: `${{ steps.app-options.outputs.version }}`
            [Rebuild](${{ github.server_url }}/${{ github.repository }}/actions/workflows/release.yaml)
          nodetail: true
          title: App build failed
          username: GitHub Actions
          url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
